apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    it execs inside target pods to run the chaos inject commands, waits for the chaos duration and reverts the chaos
kind: ChaosExperiment
metadata:
  name: sample-exec-chaos
  labels:
    name: sample-exec-chaos
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: latest
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: 
          - "" 
          - "batch" 
          - "apps" 
          - "litmuschaos.io" 
        resources: 
          - "jobs" 
          - "pods" 
          - "pods/log" 
          - "events" 
          - "deployments" 
          - "replicasets" 
          - "pods/exec" 
          - "chaosengines" 
          - "chaosexperiments" 
          - "chaosresults" 
        verbs: 
          - "create" 
          - "list" 
          - "get" 
          - "patch" 
          - "update" 
          - "delete" 
          - "deletecollection" 
    image: "mailtovivek87/litmus-python-chart-path:v3"
    imagePullPolicy: Never
    args:
    - -c
    - python3 -u experiment -name chaos
    command:
    - /bin/bash
    env:

    - name: TOTAL_CHAOS_DURATION
      value: '30' 

    - name: CHAOS_INTERVAL
      value: '30'

    - name: LIB
      value: ''

    - name: RAMP_TIME
      value: ''

    - name: APP_NAMESPACE
      value: 'litmus'

    - name: APP_LABEL
      value: 'app=nginx'

    - name: APP_KIND
      value: 'deployments'

    - name: FORCE
      value: 'true'

    - name: SEQUENCE
      value: 'parallel'
      
    labels:
      name: sample-exec-chaos-pd
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: latest 