apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: sample-category
  version: 0.1.0
  annotations:
    categories: sample-category
spec:
  displayName:  sample-exec-chaos
  categoryDescription: >
    Execute sample chaos
  experiments:
  - sample-exec-chaos
  keywords:
    - chaos
  maintainers:
    - name: oumkale
      email: oumkale@chaosnative.com
  minKubeVersion: 1.12.0
  provider:
    name: ChaosNative
  links:
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/getstarted/
  icon:
    - url:
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/sample-category/experiments.yaml