apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: sample-exec-chaos
  version: 0.1.0
  annotations:
    categories: sample-category
spec:
  displayName: sample-exec-chaos
  categoryDescription: >
    Execute sample chaos
  keywords:
    - "chaos"
  platforms:
    - "minikube"
  maturity: alpha
  maintainers:
    - name: oumkale
      email: oumkale@chaosnative.com
  minKubeVersion: 1.12.0
  provider:
    name: ChaosNative
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: latest
  links:
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/getstarted/
  icon:
    - url:
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/sample-category/sample-exec-chaos/experiment.yaml